# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6e21caffb0d29bcc6ff7366af5a30b5fb4861c08dd64e8342c12efdb3092d075785a85eae86f9d23e197bc01aa9257371a73fca4aede7fea9c9c77a088c229c

test:
  secret_key_base: 128156ff78ea1de804f3538380d275ccbec412b7789e498b1404d81e6c16655cb73e9fea7142605d24cdafd97c7b721a3d65faf225b0b05c4abb8d1e050503b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
